site:
  title: XTDB Docs
  start_page: main::index.adoc
  url: https://docs.xtdb.com
  # homeUrl: &home_url /xyz/5.2/index.html
  keys:
    mainSiteUrl: "https://xtdb.com/"
    mainSiteTitle: XTDB - Home
    # Uncomment these to enable Matomo Analytics Snippets
    # matomoUrl: "//bunseki.juxt.pro/"
    # matomoSiteId: "4"
    typesenseHost: xtagzc25w84ufq37p-1.a1.typesense.net
    typesenseApiKey: 0zVHpGQFDUhgP9hazp1laLklfy00AlGD
    typesenseCollectionName: xtdb-site-2-s3

content:
  sources:
    - url: ../
      start_path: docs/main # index
      branches: v2xtdbcom
    - url: ../
      start_path: docs/reference
      branches:
        - v2xtdbcom
#        - docs-v*
    - url: ../
      start_path: docs/tutorials
      branches: v2xtdbcom
    - url: ../
      start_path: docs/howto
      branches: v2xtdbcom
    - url: ../
      start_path: docs/articles
      branches: v2xtdbcom

ui:
  bundle:
    url: https://xtdb-ui-bundle.s3.eu-west-1.amazonaws.com/xtdb-docs-ui-v2-bundle.zip
    snapshot: true

asciidoc:
  attributes:
    page-pagination: true
  extensions:
    - ./antora-extensions/code-tabs.js
